# Generated by Django 4.2.1 on 2023-05-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduon', '0003_alter_course_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerials',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduon.course'),
        ),
    ]
