# Generated by Django 4.2.1 on 2023-05-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduon', '0004_coursematerials_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eduon.course'),
            preserve_default=False,
        ),
    ]
